<Project Sdk="Microsoft.NET.Sdk">

	<!-- See 'Directory.Build.props' for configuration related to AOT compilation, trimming, and
		 self-contained publishing. -->

	<!-- Project Core Settings -->
	<PropertyGroup Label="Project Core Settings">
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<StartupObject>DateToday.Avalonia.Program</StartupObject>
		<Nullable>enable</Nullable>
		<NeutralLanguage>en-GB</NeutralLanguage>
	</PropertyGroup>

	<!-- Avalonia Configuration -->
	<PropertyGroup Label="Avalonia Configuration">
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<!-- Analyser Configuration -->
	<PropertyGroup Label="Analyser Configuration">
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<!-- App Metadata -->
	<PropertyGroup Label="App Metadata">
		<Title>DateToday</Title>
		<Version>2.0.0</Version>
		<Description>A beautiful, lightweight desktop widget that displays the current date and/or time in a configurable format.</Description>
		<Copyright>© 2026 Josiah Danger Shaahin</Copyright>
		<RepositoryUrl>https://github.com/JosiahDanger/DateToday</RepositoryUrl>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<ApplicationIcon>DateToday Icon.ico</ApplicationIcon>
	</PropertyGroup>

	<!-- App Dependencies -->
	<ItemGroup Label="App Dependencies">
		<PackageReference Include="Avalonia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="PublishAotCompressed" Version="1.0.5" />
	</ItemGroup>

	<!-- Embedded Strings -->
	<ItemGroup Label="Embedded Strings">
		<EmbeddedResource Update="Avalonia\Resources\Strings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>

		<Compile Update="Avalonia\Resources\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<!-- Embedded Fonts -->
	<ItemGroup Label="Embedded Fonts">
		<AvaloniaResource Include="Avalonia\Fonts\*.otf" />
		<AvaloniaResource Include="Avalonia\Fonts\*.ttf" />
	</ItemGroup>

	<!-- Embedded StreamGeometry -->
	<ItemGroup Label="Embedded Fonts">
		<AvaloniaResource Include="Avalonia\Resources\IconGeometries.axaml" />
	</ItemGroup>

</Project>
