//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateToday.Avalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateToday.Avalonia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string AlertView_Button_CloseAlert {
            get {
                return ResourceManager.GetString("AlertView_Button_CloseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateToday has shat the bed..
        /// </summary>
        public static string AlertView_ErrorFlavour_Caption {
            get {
                return ResourceManager.GetString("AlertView_ErrorFlavour_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A heads-up from DateToday..
        /// </summary>
        public static string AlertView_InformationFlavour_Caption {
            get {
                return ResourceManager.GetString("AlertView_InformationFlavour_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateToday has encountered a problem..
        /// </summary>
        public static string AlertView_WarningFlavour_Caption {
            get {
                return ResourceManager.GetString("AlertView_WarningFlavour_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine the filepath of the app executable..
        /// </summary>
        public static string AppVersionProvider_Exception_ExecutableFilepathNotAvailable {
            get {
                return ResourceManager.GetString("AppVersionProvider_Exception_ExecutableFilepathNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app executable does not specify its ProductVersion..
        /// </summary>
        public static string AppVersionProvider_Exception_ExecutableVersionUnspecified {
            get {
                return ResourceManager.GetString("AppVersionProvider_Exception_ExecutableVersionUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver..
        /// </summary>
        public static string AppVersionProvider_Prefix {
            get {
                return ResourceManager.GetString("AppVersionProvider_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A converter received an unsupported member of an enumeration type..
        /// </summary>
        public static string Converter_Exception_EnumerationTypeMember_NotSupported {
            get {
                return ResourceManager.GetString("Converter_Exception_EnumerationTypeMember_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string SettingsView_TabControl_TabItem_AppTabHeader {
            get {
                return ResourceManager.GetString("SettingsView_TabControl_TabItem_AppTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string SettingsView_TabControl_TabItem_ContentTabHeader {
            get {
                return ResourceManager.GetString("SettingsView_TabControl_TabItem_ContentTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string SettingsView_TabControl_TabItem_FontTabHeader {
            get {
                return ResourceManager.GetString("SettingsView_TabControl_TabItem_FontTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SettingsView_TabControl_TabItem_PositionTabHeader {
            get {
                return ResourceManager.GetString("SettingsView_TabControl_TabItem_PositionTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Window_Title {
            get {
                return ResourceManager.GetString("SettingsView_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialise the persisted application state..
        /// </summary>
        public static string Suspension_Exception_FailedToDeserialiseState {
            get {
                return ResourceManager.GetString("Suspension_Exception_FailedToDeserialiseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your existing settings file is either inaccessible or invalid. The widget has instead been initialised using a default configuration..
        /// </summary>
        public static string Suspension_Exception_FailedToDeserialiseState_Friendly {
            get {
                return ResourceManager.GetString("Suspension_Exception_FailedToDeserialiseState_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to persist the application state..
        /// </summary>
        public static string Suspension_Exception_FailedToPersistState {
            get {
                return ResourceManager.GetString("Suspension_Exception_FailedToPersistState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app attempted to save your widget configuration, but it was unable to do so. Please ensure that the app executable is permitted write access within its containing folder..
        /// </summary>
        public static string Suspension_Exception_FailedToPersistState_Friendly {
            get {
                return ResourceManager.GetString("Suspension_Exception_FailedToPersistState_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetoday-widget-state.json.
        /// </summary>
        public static string Suspension_Filename_WidgetState {
            get {
                return ResourceManager.GetString("Suspension_Filename_WidgetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string WidgetView_ContextMenu_MenuItem_ExitApplication {
            get {
                return ResourceManager.GetString("WidgetView_ContextMenu_MenuItem_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget Settings.
        /// </summary>
        public static string WidgetView_ContextMenu_MenuItem_OpenSettingsView {
            get {
                return ResourceManager.GetString("WidgetView_ContextMenu_MenuItem_OpenSettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateToday.
        /// </summary>
        public static string WidgetView_Window_Title {
            get {
                return ResourceManager.GetString("WidgetView_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of OrdinalDaySuffixPosition must be positive..
        /// </summary>
        public static string WidgetViewModel_Exception_OrdinalDaySuffixPosition_Negative {
            get {
                return ResourceManager.GetString("WidgetViewModel_Exception_OrdinalDaySuffixPosition_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of OrdinalDaySuffixPosition exceeds the length of DateTimeFormat..
        /// </summary>
        public static string WidgetViewModel_Exception_OrdinalDaySuffixPosition_OutOfRange {
            get {
                return ResourceManager.GetString("WidgetViewModel_Exception_OrdinalDaySuffixPosition_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of RefreshIntervalSeconds must be greater than zero..
        /// </summary>
        public static string WidgetViewModel_Exception_RefreshIntervalSeconds_Zero {
            get {
                return ResourceManager.GetString("WidgetViewModel_Exception_RefreshIntervalSeconds_Zero", resourceCulture);
            }
        }
    }
}
